# Funding support for SCL339

github: # GitHub Sponsors (not available in China)
patreon: # Patreon
open_collective: # Open Collective
ko_fi: # Ko-fi
tidelift: # Tidelift
community_bridge: # Community Bridge
liberapay: # Liberapay
issuehunt: # IssueHunt
lfx_crowdfunding: # LFX Crowdfunding
polar: # Polar
buy_me_a_coffee: # Buy Me a Coffee (not available in China)
thanks_dev: # thanks.dev
custom: # Alipay is the primary sponsor method
